module.exports = [
  "He'll never overcome The trial!",
  "Oh, I love the trial!",
  "Ohhhhh.... the trial! My favorite!",
  "Does it have to be the trial?",
  "The trial! The trial!",
  "Why is it always the trial?",
  "Yesss, the trial!",
  "Ah yes, the trial...",
  "I had almost forgotten about the trial...",
  "Wait, what's the trial?",
  "No, not the trial!",
  "Yes, yes, the trial!",
  "How could he overcome the trial? He couldn't overcome a paper bag!",
  "Yes... Yes, the trial...",
];
