module.exports = [
  "Aaaah, the trial!",
  "Ah yes, the trial...",
  "Ahahaha, the trial!",
  "Ahahaha! I'd love to see this one overcome the trial!",
  "Does it have to be the trial?",
  "Excellent, excellent!",
  "Ha, this one will never overcome the trial!",
  "This one could never overcome the trial!",
  "I had almost forgotten about the trial...",
  "No, not the trial!",
  "Oh, how could I forget the trial!",
  "Oh, how I love the trial!",
  "Oh, I love the trial!",
  "Oh, I'd love to see this one try to overcome the trial!",
  "Oh, the trial! We never hear about the trial!",
  "Oh, what luck! The trial!",
  "Oh, wonderful! The trial!",
  "Oh, yes, the trial!",
  "Ohhhhh.... the trial! My favorite!",
  "The trial! Oh, how daunting!",
  "The trial! The trial!",
  "The trial! Yes, excellent choice!",
  "The trial! Yes!",
  "The trial!",
  "The trial? My favorite!",
  "Wait, what's the trial?",
  "What a good choice!",
  "Why is it always the trial?",
  "Yes, yes, tell this one about the trial!",
  "Yes, yes, the trial, good...",
  "Yes, yes, the trial!",
  "Yes, yes!",
  "Yes... Yes, the trial...",
  "Yesss, the trial!",
];
